version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  test:
    docker:
      - image: circleci/node:15.3.0
    parallelism: 1
    working_directory: ~/gondola/heroku-test-api
    steps:
      - checkout
      - attach_workspace:
          at: ~/gondola/heroku-test-api
      - restore_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v1-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths: dist
