version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@4.1.0

workflows:
  test_my_app:
    jobs:
      - node/test:
          version: 4.1.0
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - test_my_app
          filters:
            branches:
              only: main
