version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@2.0.2

jobs:
  test:
    docker:
      - image: cimg/node:15.3.0
    steps:
      - checkout
      - run: npm run test

workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          filters:
            branches:
              only: main