version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku-deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main