version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  node: circleci/node@4.1.0
workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  test:
    - node/text
      version: 4.1.0