version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - test
      - heroku/deploy-via-git:
          requires:
            - test
          filters:
            branches:
              only: main

jobs:
  test:
    executor:
      name: node/default
      tag: '13.4'
    steps:
      - checkout
      - node/install-packages
      - run:
        command: npm run test